### ISSUE TITLE
ModuleNotFound

### ISSUE THREAD

**Issue by mhmdrzkii** [Too-Naive/WelcomeBot-Telegram#4]
sir how to fix ModuleNotFoundError: No module named 'libpy3.aiopgsqldb'

**Comment by KunoiSayami** [comment]
You should use `git submodule update --init` in your repo root.

**Comment by KunoiSayami** [comment]
Check this: https://github.com/KunoiSayami/WelcomeBot-Telegram#to-clone-repo-please-use-the-following-code

**Comment by mhmdrzkii** [comment]
tried it and I don't think there is any change sir can you help me to use your bot? this will be very useful and helpful, is there a video to install it?

**Comment by mhmdrzkii** [comment]
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "d:\Data\FULL FILE\06. TEMPORARY FILES\004. TEMPORARY RAR FILES\WelcomeBot-Telegram-master\WelcomeBot-Telegram-master\welcome_bot.py", line 32, in <module>
    from cache import GroupCache, GroupProperty, PostgreSQL
  File "d:\Data\FULL FILE\06. TEMPORARY FILES\004. TEMPORARY RAR FILES\WelcomeBot-Telegram-master\WelcomeBot-Telegram-master\cache.py", line 21, in <module>
    from libpy3.aiopgsqldb import PgSQLdb
ModuleNotFoundError: No module named 'libpy3.aiopgsqldb'

**Comment by KunoiSayami** [comment]
I'm pretty sure you didn't follow our instructions on installation, check this https://asciinema.org/a/U8uiuqQJ9XmDLncUgroBXNNIm .
You should use `git clone` instead of `download zip file`

if you really need download zip file, you should also download https://github.com/KunoiSayami/libpy3/tree/848e91d8c07713bfc4ecb04243fde59d7da3e0a1 and put all file into libpy3 folder.

**Comment by mhmdrzkii** [comment]
I've done as in the video, but it happens exactly like in the video like this


 " 2022-07-16 16:55:56,587 - DEBUG - __init__ - 66 - Enter WelcomeBot.__init__()
2022-07-16 16:55:56,588 - INFO - init_receiver - 282 - Init receiver
Traceback (most recent call last):
  File "c:\Users\mhmdr\WelcomeBot-Telegram\welcome_bot.py", line 420, in <module>
    asyncio.run(main())
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "c:\Users\mhmdr\WelcomeBot-Telegram\welcome_bot.py", line 335, in main
    b = await WelcomeBot.create()
  File "c:\Users\mhmdr\WelcomeBot-Telegram\welcome_bot.py", line 106, in create
    config.get("pgsql", "host"),
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'pgsql' "

 What do you think I should configure? thanks

**Comment by KunoiSayami** [comment]
Sorry, I forget update configure file layout, please check ac184cff2ed30e1a9805ac6c0af80e64d2d45f28

**Comment by mhmdrzkii** [comment]
ok sir, until now I'm confused about how to proceed, what to do again? git updates?

**Comment by KunoiSayami** [comment]
No, just copy whole sample file and configure it, that's all.
Alright, you can also use `git pull` to update.

Don't forget `git submodule update --init` after successful pull.

**Comment by mhmdrzkii** [comment]
2022-07-17 09:43:38,508 - DEBUG - __init__ - 66 - Enter WelcomeBot.__init__()
2022-07-17 09:43:38,509 - INFO - init_receiver - 282 - Init receiver
Traceback (most recent call last):
  File "c:\Users\mhmdr\WelcomeBot-Telegram\welcome_bot.py", line 420, in <module>
    asyncio.run(main())
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "c:\Users\mhmdr\WelcomeBot-Telegram\welcome_bot.py", line 335, in main
    b = await WelcomeBot.create()
  File "c:\Users\mhmdr\WelcomeBot-Telegram\welcome_bot.py", line 105, in create
    self.conn = await PostgreSQL.create(
  File "c:\Users\mhmdr\WelcomeBot-Telegram\libpy3\aiopgsqldb.py", line 60, in create
    await self.create_connect()
  File "c:\Users\mhmdr\WelcomeBot-Telegram\libpy3\aiopgsqldb.py", line 43, in create_connect
    self.pgsql_connection = await asyncpg.connect(
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncpg\connection.py", line 2085, in connect
    return await connect_utils._connect(
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncpg\connect_utils.py", line 895, in _connect
    raise last_error
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncpg\connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncpg\connect_utils.py", line 781, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncpg\connect_utils.py", line 825, in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncpg\compat.py", line 66, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncpg\connect_utils.py", line 691, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1069, in create_connection
    raise exceptions[0]
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 705, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\mhmdr\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection

why like this sir?

**Comment by KunoiSayami** [comment]
**In principle, need python 3.7.x interpreter and PostgreSQL database**
**Import group_welcome.sql to database which you will connect**

https://github.com/KunoiSayami/WelcomeBot-Telegram#runtime-environment

**Comment by mhmdrzkii** [comment]
sir in me still

```
 from libpy3.aiopgsqldb import PgSQLdb
ModuleNotFoundError: No module named 'libpy3.aiopgsqldb'
```

**Comment by KunoiSayami** [comment]
Check your folders for files and don't ask questions that have already been answered.
